# Generated by Django 3.1.3 on 2020-11-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='user', max_length=255)),
                ('email', models.URLField(blank=True, default='user@gmail.com', max_length=255)),
                ('phone', models.CharField(blank=True, default='-', max_length=255)),
                ('objective', models.TextField(max_length=1000)),
                ('school', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('experience2', models.CharField(blank=True, max_length=255)),
                ('experience3', models.CharField(blank=True, max_length=255)),
                ('skills', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
