# Generated by Django 3.1.3 on 2020-11-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='email',
            field=models.EmailField(blank=True, default='user@gmail.com', max_length=255),
        ),
    ]
