# Generated by Django 3.1.3 on 2020-11-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20201108_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='github',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='linkedin',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
