# Generated by Django 3.1.3 on 2020-11-08 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_clientprofile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='photo',
        ),
    ]
