# Generated by Django 3.1.3 on 2020-11-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_remove_clientprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='carrer',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
